controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

api_routes:
    resource: ../../src/Controller/Api/
    type: annotation
    prefix: /api/v1
    name_prefix: api.
    options: { i18n: false }
